# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# Prompt Format Code Settings
export STYLE_BOLD=1
export STYLE_DIM=2
export STYLE_UNDERLINED=4
export STYLE_BLINK=5
export STYLE_REVERSE=7
export STYLE_HIDDEN=8

export RESET_ALL=0
export RESET_BOLD=21
export RESET_DIM=22
export RESET_UNDERLINED=24
export RESET_BLINK=25
export RESET_REVERSE=27
export RESET_HIDDEN=28

# Prompt Color Code Settings
## ForeGround Color Code
export FG_DEFAULT=39
export FG_RED=31
export FG_GREEN=32
export FG_YELLOW=33
export FG_BLUE=34
export FG_MAGENTA=35
export FG_CYAN=36
export FG_LIGHT_GRAY=34
export FG_DARK_GRAY=90
export FG_LIGHT_RED=91
export FG_LIGHT_GREEN=92
export FG_LIGHT_YELLOW=93
export FG_LIGHT_BLUE=94
export FG_LIGHT_MAGENTA=95
export FG_LIGHT_CYAN=96
export FG_WHITE=97

## BackGround Color Code
export BG_DEFAULT=49
export BG_BLACK=40
export BG_RED=41
export BG_GREEN=42
export BG_YELLOW=43
export BG_BLUE=44
export BG_MAGENTA=45
export BG_CYAN=46
export BG_LIGHT_GRAY=47
export BG_DARK_GRAY=100
export BG_LIGHT_RED=101
export BG_LIGHT_GREEN=102
export BG_LIGHT_YELLOW=103
export BG_LIGHT_BLUE=104
export BG_LIGHT_MAGENTA=105
export BG_LIGHT_CYAN=106
export BG_WHITE=107
